# Generated by Django 5.0.4 on 2024-04-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('limit', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('streak', 'Racha'), ('achiv_amount', ''), ('exer_amount', ''), ('exer_diff', ''), ('exer_type', ''), ('exer_diff_type', '')], max_length=255)),
                ('exer_difficulty', models.IntegerField(blank=True, choices=[(0, 'Principiante'), (1, 'Intermedio'), (2, 'Avanzado')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('memory', 'Memoria'), ('visualization', 'Visualización')], max_length=255)),
                ('difficulty', models.IntegerField(default=0)),
                ('image_url', models.CharField(default='/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userprofile')),
            ],
        ),
    ]
