# Generated by Django 5.0.4 on 2024-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
